package pinjamnovel;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author Septa_Hendrawan
 */
public class App extends javax.swing.JFrame {
    init init = new init();

    public App() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnl_Overlay.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Login = new javax.swing.JPanel();
        lab_username = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lab_Password = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_Login = new javax.swing.JButton();
        lab_Note = new javax.swing.JLabel();
        lab_Note2 = new javax.swing.JLabel();
        pnl_Overlay = new javax.swing.JPanel();
        icon_library = new javax.swing.JLabel();
        lab_Note1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Login.setBackground(new java.awt.Color(32, 33, 35));
        pnl_Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_username.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lab_username.setForeground(new java.awt.Color(126, 87, 194));
        lab_username.setText("Username");
        pnl_Login.add(lab_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        txt_Username.setBackground(new java.awt.Color(32, 33, 35));
        txt_Username.setForeground(java.awt.Color.lightGray);
        txt_Username.setBorder(null);
        txt_Username.setCaretColor(new java.awt.Color(255, 255, 255));
        pnl_Login.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 310, 20));
        pnl_Login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 310, 10));

        lab_Password.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lab_Password.setForeground(new java.awt.Color(126, 87, 194));
        lab_Password.setText("Password");
        pnl_Login.add(lab_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txt_Password.setBackground(new java.awt.Color(32, 33, 35));
        txt_Password.setForeground(java.awt.Color.lightGray);
        txt_Password.setBorder(null);
        txt_Password.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PasswordKeyPressed(evt);
            }
        });
        pnl_Login.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 310, 20));
        pnl_Login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, 10));

        btn_Login.setBackground(new java.awt.Color(126, 87, 194));
        btn_Login.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        pnl_Login.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, 40));

        lab_Note.setForeground(new java.awt.Color(126, 87, 194));
        lab_Note.setText("Sign up");
        lab_Note.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_NoteMouseClicked(evt);
            }
        });
        pnl_Login.add(lab_Note, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        lab_Note2.setForeground(new java.awt.Color(153, 153, 153));
        lab_Note2.setText("Don't have an account?");
        pnl_Login.add(lab_Note2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 150, -1));

        getContentPane().add(pnl_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 590));

        pnl_Overlay.setBackground(new java.awt.Color(0, 0, 0));
        pnl_Overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_library.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon Library.png"))); // NOI18N
        icon_library.setText("jLabel1");
        pnl_Overlay.add(icon_library, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, 100));

        lab_Note1.setForeground(new java.awt.Color(153, 153, 153));
        lab_Note1.setText("Management System");
        pnl_Overlay.add(lab_Note1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, 30));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        pnl_Overlay.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        getContentPane().add(pnl_Overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 390, 590));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Laptop Background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, -70, 360, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void lab_NoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_NoteMouseClicked
//        Registrasi1 reg1 = new Registrasi1();
//        reg1.show();
        new SignUp().show();
        this.dispose();
    }//GEN-LAST:event_lab_NoteMouseClicked

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        loginFunction();
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txt_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginFunction();
        }
    }//GEN-LAST:event_txt_PasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel icon_library;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lab_Note;
    private javax.swing.JLabel lab_Note1;
    private javax.swing.JLabel lab_Note2;
    private javax.swing.JLabel lab_Password;
    private javax.swing.JLabel lab_username;
    private javax.swing.JPanel pnl_Login;
    private javax.swing.JPanel pnl_Overlay;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
public void loginFunction () {
        try {
            init.Connection();
            PreparedStatement pSt = init.conn.prepareStatement("SELECT * FROM dblogin WHERE username =? and pass=?");
            
            pSt.setString(1, txt_Username.getText());
            pSt.setString(2, txt_Password.getText());
            ResultSet rs = pSt.executeQuery();
            
            if (rs.next() == true) { 
                JOptionPane.showMessageDialog(this, "Login Success!", "Information", JOptionPane.INFORMATION_MESSAGE); 
                String temp = rs.getString("nim");
                if (txt_Username.getText().toLowerCase().equals("admin")) {
                    new PageAdmin().show();
                    this.dispose();
                } else {
                    new PageUser(temp).show();
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "username atau password salah!", "Login Failed!", JOptionPane.INFORMATION_MESSAGE);
                txt_Password.setText("");
            }
        } catch (SQLException e) {
            System.out.println("Error " + e.toString());
        } 
    }
}
