package pinjamnovel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.Arrays;
import javax.swing.*;
import java.awt.Color;
import java.awt.Frame;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Robert
 */
public class PageAdmin extends javax.swing.JFrame {

    private ScheduledExecutorService executor;
    init init = new init();
    Object[][] data1 = null;
    Object[][] pinjam2 = null;
    Object[][] pinjam1 = null;
    Object[][] buku = null;
    Object[][] temp = null;
    String nama, judul_buku, nim_user, id_buku, status, tgl_pinjam, tgl_kembali, no_telp;
    int lama_pinjam;
    int xx, xy;
    int choice;
    boolean posActive1 = false, posActive2 = false, posActive3 = false, posActive4 = false, posActive5 = false;

    /**
     * Creates new form sideNavPanel
     */
    public PageAdmin() {
        initComponents();
        active(dataPengajuan, labPinjamBuku);
        conActive(content_1, content_2, content_3, content_4, content_5);
        executor = Executors.newScheduledThreadPool(1);

        Runnable task = new Runnable() {
            public void run() {
                tampilTabel();
                tampilTabelClick();
                tampilTabelPinjam1(getData1("SELECT * FROM datapinjaman_pending"));
                tampilTabelPinjam2(getData1("SELECT * FROM datapinjaman"));
                pinjam1 = init.getData(pinjam1, "SELECT * FROM datapinjaman_pending", 8);
                pinjam2 = init.getData(pinjam2, "SELECT * FROM datapinjaman", 8);
            }
        };
        executor.scheduleAtFixedRate(task, 0, 5, TimeUnit.SECONDS);

        tampilTabel();
        tampilTabelClick();
        pinjam1 = init.getData(pinjam1, "SELECT * FROM datapinjaman_pending", 8);
        pinjam2 = init.getData(pinjam2, "SELECT * FROM datapinjaman", 8);
        tampilTabelPinjam1(getData1("SELECT * FROM datapinjaman_pending"));
        tampilTabelPinjam2(getData1("SELECT * FROM datapinjaman"));
        autoComboBox();
        cmbID.setSelectedIndex(0);
        this.setLocationRelativeTo(null);
        cmbGenre.setSelectedIndex(-1);
        cmbGenre1.setSelectedIndex(-1);
        txtID1.setEditable(false);
        temp = init.getData(buku, "SELECT * FROM buku", 6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitlebar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        maximize = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        minimize = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        sideNav = new javax.swing.JPanel();
        dataPengajuan = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        labPinjamBuku = new javax.swing.JLabel();
        dataPinjam = new javax.swing.JPanel();
        labDataPinjam = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        perbaruiBuku = new javax.swing.JPanel();
        labPerbaruiBuku = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tmbhBuku = new javax.swing.JPanel();
        labTmbhBuku = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pengaturan = new javax.swing.JPanel();
        labPengaturan = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        pnlContent = new javax.swing.JPanel();
        content_1 = new javax.swing.JPanel();
        body1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        footer1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labNama = new javax.swing.JLabel();
        labJudul = new javax.swing.JLabel();
        labId = new javax.swing.JLabel();
        btnTolak = new javax.swing.JButton();
        btnAcc = new javax.swing.JButton();
        content_2 = new javax.swing.JPanel();
        body2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        footer2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        labId2 = new javax.swing.JLabel();
        labJudul2 = new javax.swing.JLabel();
        labNama2 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        content_3 = new javax.swing.JPanel();
        body3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtJudul1 = new javax.swing.JTextField();
        txtPenulis1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtTerbit1 = new javax.swing.JTextField();
        cmbGenre1 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        footer3 = new javax.swing.JPanel();
        content_4 = new javax.swing.JPanel();
        body4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbID = new javax.swing.JComboBox<>();
        txtJudul = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPenulis = new javax.swing.JTextField();
        txtTerbit = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cmbGenre = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        footer4 = new javax.swing.JPanel();
        content_5 = new javax.swing.JPanel();
        body5 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        txtPasslama = new javax.swing.JPasswordField();
        txtPassbaru = new javax.swing.JPasswordField();
        txtPassbaru2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSavepass = new javax.swing.JButton();
        footer5 = new javax.swing.JPanel();
        btnLogOut3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setUndecorated(true);

        pnlTitlebar.setBackground(new java.awt.Color(0, 0, 0));
        pnlTitlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitlebarMouseDragged(evt);
            }
        });
        pnlTitlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTitlebarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitlebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlTitlebarMouseReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        close.setBackground(new java.awt.Color(0, 0, 0));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jLabel40.setText("jLabel30");
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        maximize.setBackground(new java.awt.Color(0, 0, 0));
        maximize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                maximizeMouseReleased(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/maximize.png"))); // NOI18N
        jLabel41.setText("jLabel30");
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout maximizeLayout = new javax.swing.GroupLayout(maximize);
        maximize.setLayout(maximizeLayout);
        maximizeLayout.setHorizontalGroup(
            maximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maximizeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        maximizeLayout.setVerticalGroup(
            maximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maximizeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        minimize.setBackground(new java.awt.Color(0, 0, 0));
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize.png"))); // NOI18N
        jLabel42.setText("jLabel30");
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout minimizeLayout = new javax.swing.GroupLayout(minimize);
        minimize.setLayout(minimizeLayout);
        minimizeLayout.setHorizontalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimizeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        minimizeLayout.setVerticalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(maximize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(maximize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Library Management");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlTitlebarLayout = new javax.swing.GroupLayout(pnlTitlebar);
        pnlTitlebar.setLayout(pnlTitlebarLayout);
        pnlTitlebarLayout.setHorizontalGroup(
            pnlTitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitlebarLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 822, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTitlebarLayout.setVerticalGroup(
            pnlTitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlTitlebar, java.awt.BorderLayout.PAGE_START);

        pnlMain.setPreferredSize(new java.awt.Dimension(1089, 588));
        pnlMain.setLayout(new java.awt.BorderLayout());

        sideNav.setBackground(new java.awt.Color(51, 51, 51));
        sideNav.setPreferredSize(new java.awt.Dimension(174, 588));
        sideNav.setRequestFocusEnabled(false);

        dataPengajuan.setBackground(new java.awt.Color(51, 51, 51));
        dataPengajuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataPengajuan.setPreferredSize(new java.awt.Dimension(163, 60));
        dataPengajuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPengajuanMouseClicked(evt);
            }
        });

        labPinjamBuku.setText("Data Pengajuan");

        javax.swing.GroupLayout dataPengajuanLayout = new javax.swing.GroupLayout(dataPengajuan);
        dataPengajuan.setLayout(dataPengajuanLayout);
        dataPengajuanLayout.setHorizontalGroup(
            dataPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(dataPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPengajuanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labPinjamBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dataPengajuanLayout.setVerticalGroup(
            dataPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPengajuanLayout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(dataPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPengajuanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labPinjamBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        dataPinjam.setBackground(new java.awt.Color(51, 51, 51));
        dataPinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPinjamMouseClicked(evt);
            }
        });

        labDataPinjam.setForeground(new java.awt.Color(255, 255, 255));
        labDataPinjam.setText("Data Pinjaman");

        javax.swing.GroupLayout dataPinjamLayout = new javax.swing.GroupLayout(dataPinjam);
        dataPinjam.setLayout(dataPinjamLayout);
        dataPinjamLayout.setHorizontalGroup(
            dataPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(dataPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPinjamLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labDataPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dataPinjamLayout.setVerticalGroup(
            dataPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPinjamLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
            .addGroup(dataPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPinjamLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labDataPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        perbaruiBuku.setBackground(new java.awt.Color(51, 51, 51));
        perbaruiBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perbaruiBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perbaruiBukuMouseClicked(evt);
            }
        });

        labPerbaruiBuku.setForeground(new java.awt.Color(255, 255, 255));
        labPerbaruiBuku.setText("Perbarui Buku");

        javax.swing.GroupLayout perbaruiBukuLayout = new javax.swing.GroupLayout(perbaruiBuku);
        perbaruiBuku.setLayout(perbaruiBukuLayout);
        perbaruiBukuLayout.setHorizontalGroup(
            perbaruiBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(perbaruiBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(perbaruiBukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labPerbaruiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
        perbaruiBukuLayout.setVerticalGroup(
            perbaruiBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perbaruiBukuLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(perbaruiBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(perbaruiBukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labPerbaruiBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon-Library-small.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        tmbhBuku.setBackground(new java.awt.Color(51, 51, 51));
        tmbhBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tmbhBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmbhBukuMouseClicked(evt);
            }
        });

        labTmbhBuku.setForeground(new java.awt.Color(255, 255, 255));
        labTmbhBuku.setText("Tambah Buku");

        javax.swing.GroupLayout tmbhBukuLayout = new javax.swing.GroupLayout(tmbhBuku);
        tmbhBuku.setLayout(tmbhBukuLayout);
        tmbhBukuLayout.setHorizontalGroup(
            tmbhBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(tmbhBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tmbhBukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labTmbhBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        tmbhBukuLayout.setVerticalGroup(
            tmbhBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tmbhBukuLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(tmbhBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tmbhBukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labTmbhBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pengaturan.setBackground(new java.awt.Color(51, 51, 51));
        pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengaturanMouseClicked(evt);
            }
        });

        labPengaturan.setForeground(new java.awt.Color(255, 255, 255));
        labPengaturan.setText("Pengaturan / Log Out");

        javax.swing.GroupLayout pengaturanLayout = new javax.swing.GroupLayout(pengaturan);
        pengaturan.setLayout(pengaturanLayout);
        pengaturanLayout.setHorizontalGroup(
            pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pengaturanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pengaturanLayout.setVerticalGroup(
            pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengaturanLayout.createSequentialGroup()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(pengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pengaturanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout sideNavLayout = new javax.swing.GroupLayout(sideNav);
        sideNav.setLayout(sideNavLayout);
        sideNavLayout.setHorizontalGroup(
            sideNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataPengajuan, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
            .addComponent(dataPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(perbaruiBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideNavLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(tmbhBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideNavLayout.setVerticalGroup(
            sideNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideNavLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(dataPengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dataPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(perbaruiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tmbhBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pnlMain.add(sideNav, java.awt.BorderLayout.WEST);

        pnlContent.setLayout(new java.awt.CardLayout());

        content_1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout body1Layout = new javax.swing.GroupLayout(body1);
        body1.setLayout(body1Layout);
        body1Layout.setHorizontalGroup(
            body1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE))
        );
        body1Layout.setVerticalGroup(
            body1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        content_1.add(body1, java.awt.BorderLayout.CENTER);

        footer1.setBackground(new java.awt.Color(204, 204, 204));
        footer1.setMaximumSize(new java.awt.Dimension(926, 129));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ID Buku");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Judul Buku");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nama Peminjam");

        labNama.setText("...");

        labJudul.setText("...");

        labId.setText("...");

        btnTolak.setText("Tolak");
        btnTolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolakActionPerformed(evt);
            }
        });

        btnAcc.setText("Setujui");
        btnAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footer1Layout = new javax.swing.GroupLayout(footer1);
        footer1.setLayout(footer1Layout);
        footer1Layout.setHorizontalGroup(
            footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(footer1Layout.createSequentialGroup()
                        .addComponent(labId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(labNama, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(349, 349, 349)
                .addComponent(btnTolak)
                .addGap(18, 18, 18)
                .addComponent(btnAcc)
                .addGap(20, 20, 20))
        );
        footer1Layout.setVerticalGroup(
            footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footer1Layout.createSequentialGroup()
                .addGroup(footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(footer1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTolak)
                            .addComponent(btnAcc)))
                    .addGroup(footer1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(labNama)
                                .addComponent(labId))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labJudul))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        content_1.add(footer1, java.awt.BorderLayout.PAGE_END);

        pnlContent.add(content_1, "card2");

        content_2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout body2Layout = new javax.swing.GroupLayout(body2);
        body2.setLayout(body2Layout);
        body2Layout.setHorizontalGroup(
            body2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(body2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(body2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        body2Layout.setVerticalGroup(
            body2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(body2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(body2Layout.createSequentialGroup()
                    .addGap(0, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 262, Short.MAX_VALUE)))
        );

        content_2.add(body2, java.awt.BorderLayout.CENTER);

        footer2.setBackground(new java.awt.Color(204, 204, 204));
        footer2.setMaximumSize(new java.awt.Dimension(926, 129));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("ID Buku");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Judul Buku");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Nama Peminjam");

        labId2.setText("...");

        labJudul2.setText("...");

        labNama2.setText("...");

        btnKembali.setText("Kembalikan");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footer2Layout = new javax.swing.GroupLayout(footer2);
        footer2.setLayout(footer2Layout);
        footer2Layout.setHorizontalGroup(
            footer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footer2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel32))
                .addGap(109, 109, 109)
                .addGroup(footer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labId2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labJudul2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(footer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(footer2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)
                        .addGap(24, 24, 24))
                    .addGroup(footer2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(labNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(405, Short.MAX_VALUE))))
        );
        footer2Layout.setVerticalGroup(
            footer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footer2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKembali)
                    .addGroup(footer2Layout.createSequentialGroup()
                        .addGroup(footer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(labId2)
                            .addComponent(jLabel25)
                            .addComponent(labNama2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(footer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labJudul2)
                            .addComponent(jLabel32))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        content_2.add(footer2, java.awt.BorderLayout.PAGE_END);

        pnlContent.add(content_2, "card2");

        content_3.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel12.setText("ID Buku");

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel33.setText("Judul");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel14.setText("Penulis");

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel34.setText("Tahun Terbit");

        cmbGenre1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Komedi", "Fiksi Ilmiah", "Horor", "Romantis", "Sejarah", "Misteri" }));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel35.setText("Genre");

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel36.setText("Status");

        txtStatus.setText("...");

        btnEdit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEdit.setText("Perbarui dan Simpan");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnHapus.setText("Hapus Buku");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout body3Layout = new javax.swing.GroupLayout(body3);
        body3.setLayout(body3Layout);
        body3Layout.setHorizontalGroup(
            body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(body3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(116, 116, 116)
                        .addComponent(txtJudul1))
                    .addGroup(body3Layout.createSequentialGroup()
                        .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))
                        .addGap(107, 107, 107)
                        .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body3Layout.createSequentialGroup()
                                .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(116, 116, 116)
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbGenre1, 0, 749, Short.MAX_VALUE)))
                    .addGroup(body3Layout.createSequentialGroup()
                        .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel34))
                        .addGap(70, 70, 70)
                        .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID1)
                            .addComponent(txtTerbit1)
                            .addComponent(txtPenulis1))))
                .addContainerGap())
        );
        body3Layout.setVerticalGroup(
            body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(txtJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPenulis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(txtTerbit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(cmbGenre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(txtStatus)
                    .addGroup(body3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHapus)
                        .addComponent(btnEdit)))
                .addContainerGap())
        );

        content_3.add(body3, java.awt.BorderLayout.CENTER);

        footer3.setBackground(new java.awt.Color(204, 204, 204));
        footer3.setMaximumSize(new java.awt.Dimension(926, 129));

        javax.swing.GroupLayout footer3Layout = new javax.swing.GroupLayout(footer3);
        footer3.setLayout(footer3Layout);
        footer3Layout.setHorizontalGroup(
            footer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        footer3Layout.setVerticalGroup(
            footer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        content_3.add(footer3, java.awt.BorderLayout.PAGE_END);

        pnlContent.add(content_3, "card2");

        content_4.setLayout(new java.awt.BorderLayout());

        jLabel8.setBackground(new java.awt.Color(204, 255, 255));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("ID Buku");

        jLabel9.setBackground(new java.awt.Color(204, 255, 255));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText("Judul");

        jLabel10.setBackground(new java.awt.Color(204, 255, 255));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setText("Penulis");

        jLabel37.setBackground(new java.awt.Color(204, 255, 255));
        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel37.setText("Tahun Terbit");

        jLabel38.setBackground(new java.awt.Color(204, 255, 255));
        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel38.setText("Genre");

        cmbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Komedi", "Fiksi Ilmiah", "Horor", "Romantis", "Sejarah", "Misteri" }));

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout body4Layout = new javax.swing.GroupLayout(body4);
        body4.setLayout(body4Layout);
        body4Layout.setHorizontalGroup(
            body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(body4Layout.createSequentialGroup()
                        .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))
                        .addGap(77, 77, 77)
                        .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJudul)
                            .addComponent(txtPenulis)
                            .addComponent(txtTerbit)
                            .addComponent(cmbGenre, 0, 746, Short.MAX_VALUE)
                            .addGroup(body4Layout.createSequentialGroup()
                                .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSimpan)
                                    .addComponent(cmbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        body4Layout.setVerticalGroup(
            body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(body4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(cmbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        content_4.add(body4, java.awt.BorderLayout.CENTER);

        footer4.setBackground(new java.awt.Color(204, 204, 204));
        footer4.setMaximumSize(new java.awt.Dimension(926, 129));

        javax.swing.GroupLayout footer4Layout = new javax.swing.GroupLayout(footer4);
        footer4.setLayout(footer4Layout);
        footer4Layout.setHorizontalGroup(
            footer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        footer4Layout.setVerticalGroup(
            footer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        content_4.add(footer4, java.awt.BorderLayout.PAGE_END);

        pnlContent.add(content_4, "card2");

        content_5.setLayout(new java.awt.BorderLayout());

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel39.setText("Ubah Kata Sandi Admin");

        txtPassbaru2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassbaru2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Konfirmasi Kata Sandi Baru");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Kata Sandi Baru");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Kata Sandi Lama");

        btnSavepass.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSavepass.setText("Simpan");
        btnSavepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavepassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout body5Layout = new javax.swing.GroupLayout(body5);
        body5.setLayout(body5Layout);
        body5Layout.setHorizontalGroup(
            body5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(body5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, body5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46)
                        .addGroup(body5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSavepass)
                            .addGroup(body5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPassbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassbaru2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPasslama, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        body5Layout.setVerticalGroup(
            body5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel39)
                .addGap(38, 38, 38)
                .addGroup(body5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPasslama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPassbaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(body5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPassbaru2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSavepass)
                .addContainerGap())
        );

        content_5.add(body5, java.awt.BorderLayout.CENTER);

        footer5.setBackground(new java.awt.Color(204, 204, 204));
        footer5.setMaximumSize(new java.awt.Dimension(926, 129));

        btnLogOut3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnLogOut3.setText("Log out");
        btnLogOut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footer5Layout = new javax.swing.GroupLayout(footer5);
        footer5.setLayout(footer5Layout);
        footer5Layout.setHorizontalGroup(
            footer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footer5Layout.createSequentialGroup()
                .addContainerGap(804, Short.MAX_VALUE)
                .addComponent(btnLogOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        footer5Layout.setVerticalGroup(
            footer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footer5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnLogOut3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        content_5.add(footer5, java.awt.BorderLayout.PAGE_END);

        pnlContent.add(content_5, "card2");

        pnlMain.add(pnlContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPinjamMouseClicked
        // TODO add your handling code here:
        active(dataPinjam, labDataPinjam);
        nonactive(dataPengajuan, labPinjamBuku);
        nonactive(perbaruiBuku, labPerbaruiBuku);
        nonactive(tmbhBuku, labTmbhBuku);
        nonactive(pengaturan, labPengaturan);
        conActive(content_2, content_1, content_3, content_4, content_5);
    }//GEN-LAST:event_dataPinjamMouseClicked

    private void perbaruiBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbaruiBukuMouseClicked
        // TODO add your handling code here:
        active(perbaruiBuku, labPerbaruiBuku);
        nonactive(dataPengajuan, labPinjamBuku);
        nonactive(dataPinjam, labDataPinjam);
        nonactive(tmbhBuku, labTmbhBuku);
        nonactive(pengaturan, labPengaturan);
        conActive(content_3, content_2, content_1, content_4, content_5);
    }//GEN-LAST:event_perbaruiBukuMouseClicked

    private void dataPengajuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPengajuanMouseClicked
        // TODO add your handling code here
        active(dataPengajuan, labPinjamBuku);
        nonactive(dataPinjam, labDataPinjam);
        nonactive(perbaruiBuku, labPerbaruiBuku);
        nonactive(tmbhBuku, labTmbhBuku);
        nonactive(pengaturan, labPengaturan);
        conActive(content_1, content_2, content_3, content_4, content_5);
    }//GEN-LAST:event_dataPengajuanMouseClicked

    private void btnAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccActionPerformed
        try {
            init.Connection();
            PreparedStatement pSt = init.conn.prepareStatement("INSERT INTO datapinjaman SELECT * FROM datapinjaman_pending WHERE id_buku = ?");
            pSt.setString(1, labId.getText());

            if (pSt.executeUpdate() > 0) {
                try {
                    PreparedStatement pSta = init.conn.prepareStatement("UPDATE datapinjaman SET stat = 'Dipinjam' WHERE id_buku = ?");
                    pSta.setString(1, labId.getText());

                    if (pSta.executeUpdate() > 0) {
                        try {
                            PreparedStatement pStat = init.conn.prepareStatement("DELETE FROM datapinjaman_pending WHERE id_buku = ? ");
                            pStat.setString(1, labId.getText());

                            if (pStat.executeUpdate() > 0) {
                                try {
                                    PreparedStatement pStatement = init.conn.prepareStatement("INSERT INTO notif (nim,notifikasi,nama_mahasiswa,judul_buku,id_buku) VALUES (?,?,?,?,?)");
                                    pStatement.setString(1, nim_user);
                                    pStatement.setString(2, "Disetujui");
                                    pStatement.setString(3, nama);
                                    pStatement.setString(4, judul_buku);
                                    pStatement.setString(5, labId.getText());

                                    if (pStatement.executeUpdate() > 0) {
                                        pinjam1 = init.getData(pinjam1, "SELECT * FROM datapinjaman_pending", 8);
                                        pinjam2 = init.getData(pinjam2, "SELECT * FROM datapinjaman", 8);
                                        JOptionPane.showMessageDialog(this, "Berhasil Di Setujui", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                                        tampilTabelPinjam1(getData1("SELECT * FROM datapinjaman_pending"));
                                        tampilTabelPinjam2(getData1("SELECT * FROM datapinjaman"));
                                        labNama.setText("...");
                                        labJudul.setText("...");
                                        labId.setText("...");
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Gagal Di Setujui", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                                    }
                                } catch (Exception e) {
                                    System.out.println("Error " + e.toString());
                                }
                            }
                        } catch (Exception e) {
                            System.out.println("Error " + e.toString());
                        }
                    }
                } catch (Exception e) {
                    System.out.println("Error " + e.toString());
                }

            }
        } catch (SQLException e) {
            System.out.println("Error " + e.toString());
        }
    }//GEN-LAST:event_btnAccActionPerformed

    private void btnTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakActionPerformed
        String alasan = (String) JOptionPane.showInputDialog(null, "Masukan alasan mengapa pengajuan ditolak", "Informasi", JOptionPane.PLAIN_MESSAGE, null, null, null);
        if (alasan != null) {
            try {
                init.Connection();
                PreparedStatement pStatement = init.conn.prepareStatement("DELETE FROM datapinjaman_pending WHERE id_buku = ?");
                pStatement.setString(1, labId.getText());

                if (pStatement.executeUpdate() > 0) {
                    try {
                        PreparedStatement pS = init.conn.prepareStatement("UPDATE buku SET stat = 'Tersedia' WHERE id_buku = ?");
                        pS.setString(1, labId.getText());

                        PreparedStatement pSt = init.conn.prepareStatement("INSERT INTO notif (nim,notifikasi,nama_mahasiswa,judul_buku,id_buku,alasan) VALUES (?,?,?,?,?,?)");
                        pSt.setString(1, nim_user);
                        pSt.setString(2, "DiTolak");
                        pSt.setString(3, nama);
                        pSt.setString(4, judul_buku);
                        pSt.setString(5, labId.getText());
                        pSt.setString(6, alasan);

                        if (pS.executeUpdate() > 0 && pSt.executeUpdate() > 0) {
                            pinjam1 = init.getData(pinjam1, "SELECT * FROM datapinjaman_pending", 8);
                            pinjam2 = init.getData(pinjam2, "SELECT * FROM datapinjaman", 8);
                            JOptionPane.showMessageDialog(this, "Peminjaman Berhasil Ditolak", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                            tampilTabelPinjam1(getData1("SELECT * FROM datapinjaman_pending"));
                            tampilTabelPinjam2();
                            labNama.setText("...");
                            labJudul.setText("...");
                            labId.setText("...");
                        } else {
                            JOptionPane.showMessageDialog(this, "Peminjaman Gagal Ditolak", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (Exception e) {
                        System.out.println("Erroasdr " + e.toString());
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Peminjaman Gagal Ditolak", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (Exception e) {
                System.out.println("Error123 " + e.toString());
            }
        }
    }//GEN-LAST:event_btnTolakActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            init.Connection();

            PreparedStatement pStatement = init.conn.prepareStatement("UPDATE buku SET judul_buku = ?, penulis_buku = ?, tahun_terbit = ?, genre_buku = ?, stat = ?  WHERE id_buku = ?");
            pStatement.setString(1, txtJudul1.getText());
            pStatement.setString(2, txtPenulis1.getText());
            pStatement.setString(3, txtTerbit1.getText());
            pStatement.setString(4, cmbGenre1.getSelectedItem().toString());
            pStatement.setString(5, txtStatus.getText());
            pStatement.setString(6, txtID1.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Perbarui Sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Perbarui Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            tampilTabel();
            tampilTabelClick();
            autoComboBox();
            txtID1.setText("");
            txtJudul1.setText("");
            txtPenulis1.setText("");
            txtStatus.setText("");
            txtTerbit1.setText("");
            cmbGenre1.setSelectedIndex(-1);
            cmbID.setSelectedIndex(0);
        } catch (SQLException e) {
            System.out.println("Error " + e.toString());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            init.Connection();
            PreparedStatement pStatement = init.conn.prepareStatement("DELETE FROM buku WHERE id_buku = ? ");
            pStatement.setString(1, txtID1.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Hapus Sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Hapus Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            init.conn.close();
            tampilTabel();
            tampilTabelClick();
            autoComboBox();
            txtID1.setText("");
            txtJudul1.setText("");
            txtPenulis1.setText("");
            txtStatus.setText("");
            cmbGenre1.setSelectedIndex(-1);
            cmbID.setSelectedIndex(0);
        } catch (SQLException e) {
            System.out.println("Error " + e.toString());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (cekIdBuku() == false) {
            JOptionPane.showMessageDialog(this, "Id Buku sudah digunakan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (cmbID.getSelectedItem().toString().isEmpty() || txtJudul.getText().equals("") || txtPenulis.getText().equals("") || txtJudul.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukan data dengan lengkap terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                init.Connection();
                PreparedStatement pStatement = init.conn.prepareStatement("INSERT INTO buku (id_buku,judul_buku,penulis_buku,tahun_terbit,genre_buku,stat) VALUES (?,?,?,?,?,?)");
                pStatement.setString(1, "BK" + cmbID.getSelectedItem().toString());
                pStatement.setString(2, txtJudul.getText());
                pStatement.setString(3, txtPenulis.getText());
                pStatement.setString(4, txtTerbit.getText());
                pStatement.setString(5, cmbGenre.getSelectedItem().toString());
                pStatement.setString(6, "Tersedia");

                if (pStatement.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Penambahan Sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Penambahan Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                tampilTabel();
                tampilTabelClick();
                autoComboBox();
                txtJudul.setText("");
                txtPenulis.setText("");
                cmbGenre.setSelectedIndex(-1);
                cmbID.setSelectedIndex(0);
                temp = init.getData(buku, "SELECT * FROM buku", 6);
            } catch (SQLException e) {
                System.out.println("Error " + e.toString());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSavepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavepassActionPerformed
        if (Arrays.equals(txtPassbaru.getPassword(), txtPassbaru2.getPassword())) {
            try {
                init.Connection();

                PreparedStatement pStatement = init.conn.prepareStatement("SELECT * FROM dblogin WHERE username = 'admin' AND pass = ?");
                pStatement.setString(1, txtPasslama.getText());
                ResultSet rs = pStatement.executeQuery();

                if (rs.next() == true) {
                    ubahPass();
                } else {
                    JOptionPane.showMessageDialog(this, "Password lama tidak sesuai!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException e) {
                System.out.println("Error " + e.toString());
            }
        } else if (txtPassbaru.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukkan Password Anda", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (txtPassbaru2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Konfirmasi Password Anda", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Password yang anda masukan tidak sama", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSavepassActionPerformed

    private void tmbhBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbhBukuMouseClicked
        // TODO add your handling code here:
        active(tmbhBuku, labTmbhBuku);
        nonactive(dataPengajuan, labPinjamBuku);
        nonactive(perbaruiBuku, labPerbaruiBuku);
        nonactive(dataPinjam, labDataPinjam);
        nonactive(pengaturan, labPengaturan);
        conActive(content_4, content_2, content_3, content_1, content_5);
    }//GEN-LAST:event_tmbhBukuMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        close.setBackground(Color.red);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setBackground(pnlTitlebar.getBackground());
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    private void maximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseEntered
        // TODO add your handling code here:
        maximize.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_maximizeMouseEntered

    private void maximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseExited
        // TODO add your handling code here:
        maximize.setBackground(pnlTitlebar.getBackground());
    }//GEN-LAST:event_maximizeMouseExited

    private void maximizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseReleased
        // TODO add your handling code here:
        if (PageAdmin.this.getExtendedState() == MAXIMIZED_BOTH) {
            PageAdmin.this.setExtendedState(JFrame.NORMAL);
        } else {
            PageAdmin.this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_maximizeMouseReleased

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
        minimize.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:
        minimize.setBackground(pnlTitlebar.getBackground());
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        // TODO add your handling code here:
        PageAdmin.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void pnlTitlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitlebarMouseDragged
        // TODO add your handling code here:\
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTitlebarMouseDragged

    private void pnlTitlebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitlebarMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (PageAdmin.this.getExtendedState() == MAXIMIZED_BOTH) {
                PageAdmin.this.setExtendedState(JFrame.NORMAL);
            } else {
                PageAdmin.this.setExtendedState(MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_pnlTitlebarMouseClicked

    private void pnlTitlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitlebarMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTitlebarMousePressed

    private void pnlTitlebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitlebarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTitlebarMouseReleased

    private void pengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseClicked
        active(pengaturan, labPengaturan);
        nonactive(dataPengajuan, labPinjamBuku);
        nonactive(perbaruiBuku, labPerbaruiBuku);
        nonactive(tmbhBuku, labTmbhBuku);
        nonactive(dataPinjam, labDataPinjam);
        conActive(content_5, content_2, content_3, content_4, content_1);
    }//GEN-LAST:event_pengaturanMouseClicked

    private void btnLogOut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut3ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin log out?", "Informasi", JOptionPane.YES_NO_OPTION);

        if (a == JOptionPane.YES_OPTION) {
            executor.shutdown();
            executor.shutdownNow();
            this.dispose();
            new App().show();
        }
    }//GEN-LAST:event_btnLogOut3ActionPerformed

    private void txtPassbaru2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassbaru2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassbaru2ActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed

        try {
            init.Connection();
            PreparedStatement PST = init.conn.prepareStatement("UPDATE buku SET stat = 'Tersedia' WHERE id_buku = ?");
            PST.setString(1, labId2.getText());

            if (PST.executeUpdate() > 0) {
                tampilTabel();
                tampilTabelClick();
                try {
                    init.Connection();

                    PreparedStatement pStatement = init.conn.prepareStatement("DELETE FROM datapinjaman WHERE id_buku = ? ");
                    pStatement.setString(1, labId2.getText());

                    if (pStatement.executeUpdate() > 0) {
                        pinjam2 = init.getData(pinjam2, "SELECT * FROM datapinjaman", 8);
                        JOptionPane.showMessageDialog(this, "Pengembalian Berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        tampilTabelPinjam2(getData1("SELECT * FROM datapinjaman"));
                        labNama2.setText("...");
                        labJudul2.setText("...");
                        labId2.setText("...");
                    } else {
                        JOptionPane.showMessageDialog(this, "Pengembalian Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    }
                    pStatement.close();
                    init.conn.close();
                } catch (SQLException e) {
                    System.out.println("Error " + e.toString());
                }
            }
            PST.close();
            init.conn.close();
        } catch (SQLException e) {
            System.out.println("Error " + e.toString());
        } catch (Exception e) {
            System.out.println("Error " + e.toString());
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body1;
    private javax.swing.JPanel body2;
    private javax.swing.JPanel body3;
    private javax.swing.JPanel body4;
    private javax.swing.JPanel body5;
    private javax.swing.JButton btnAcc;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLogOut3;
    private javax.swing.JButton btnSavepass;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTolak;
    private javax.swing.JPanel close;
    public javax.swing.JComboBox<String> cmbGenre;
    public javax.swing.JComboBox<String> cmbGenre1;
    private javax.swing.JComboBox<String> cmbID;
    private javax.swing.JPanel content_1;
    private javax.swing.JPanel content_2;
    private javax.swing.JPanel content_3;
    private javax.swing.JPanel content_4;
    private javax.swing.JPanel content_5;
    private javax.swing.JPanel dataPengajuan;
    private javax.swing.JPanel dataPinjam;
    private javax.swing.JPanel footer1;
    private javax.swing.JPanel footer2;
    private javax.swing.JPanel footer3;
    private javax.swing.JPanel footer4;
    private javax.swing.JPanel footer5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labDataPinjam;
    private javax.swing.JLabel labId;
    private javax.swing.JLabel labId2;
    private javax.swing.JLabel labJudul;
    private javax.swing.JLabel labJudul2;
    private javax.swing.JLabel labNama;
    private javax.swing.JLabel labNama2;
    private javax.swing.JLabel labPengaturan;
    private javax.swing.JLabel labPerbaruiBuku;
    private javax.swing.JLabel labPinjamBuku;
    private javax.swing.JLabel labTmbhBuku;
    private javax.swing.JPanel maximize;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel pengaturan;
    private javax.swing.JPanel perbaruiBuku;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTitlebar;
    private javax.swing.JPanel sideNav;
    private javax.swing.JPanel tmbhBuku;
    public javax.swing.JTextField txtID1;
    public javax.swing.JTextField txtJudul;
    public javax.swing.JTextField txtJudul1;
    public javax.swing.JPasswordField txtPassbaru;
    public javax.swing.JPasswordField txtPassbaru2;
    public javax.swing.JPasswordField txtPasslama;
    public javax.swing.JTextField txtPenulis;
    public javax.swing.JTextField txtPenulis1;
    private javax.swing.JLabel txtStatus;
    public javax.swing.JTextField txtTerbit;
    public javax.swing.JTextField txtTerbit1;
    // End of variables declaration//GEN-END:variables

    public void active(JPanel panel, JLabel lab) {
        panel.setBackground(content_1.getBackground());
        lab.setForeground(Color.black);
    }

    public void nonactive(JPanel panel, JLabel lab) {
        panel.setBackground(sideNav.getBackground());
        lab.setForeground(Color.white);
    }

    public void conActive(JPanel panel, JPanel panel1, JPanel panel2, JPanel panel3, JPanel panel4) {
        panel.setVisible(true);
        panel1.setVisible(false);
        panel2.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(false);
    }

    public Object[][] getData1(String query) {
        try {
            init.Connection();

            Statement st = init.conn.createStatement(
                    ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery(query);

            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();
            data1 = new Object[rowCount][8];
            int no = -1;
            while (rs.next()) {
                no = no + 1;
                data1[no][0] = rs.getString("nim");
                data1[no][1] = rs.getString("nama");
                data1[no][2] = rs.getString("no_telp");
                data1[no][3] = rs.getString("id_buku");
                data1[no][4] = rs.getString("judul_buku");
                data1[no][5] = rs.getString("stat");
                data1[no][6] = rs.getString("tanggal_pinjam");
                data1[no][7] = rs.getString("tanggal_pengembalian");
            }
            st.close();
            init.conn.close();
        } catch (SQLException e) {
            System.out.println("Error " + e.getMessage());
        }
        return data1;
    }

    private void tampilTabelPinjam1(Object[][] data) {
        String[] columnNames = {"NIM", "Nama", "No Telp", "ID Buku", "Judul Buku", "Status", "Tanggal Pinjam", "Tanggal Pengembalian"};
        JTable tabel2 = new JTable(data, columnNames);
        jScrollPane3.setViewportView(tabel2);
        tabel2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tabel2.rowAtPoint(e.getPoint());
                int cols = tabel2.columnAtPoint(e.getPoint());
                if (row >= 0 && cols >= 0) {
                    nim_user = pinjam1[row][0].toString();
                    nama = pinjam1[row][1].toString();
                    judul_buku = pinjam1[row][4].toString();
                    labId.setText(pinjam1[row][3].toString());
                    labJudul.setText(pinjam1[row][4].toString());
                    labNama.setText(pinjam1[row][1].toString());
                }
            }
        });
    }

    private void tampilTabelPinjam2(Object[][] data) {
        String[] columnNames = {"NIM", "Nama", "No Telp", "ID Buku", "Judul Buku", "Status", "Tanggal Pinjam", "Tanggal Pengembalian"};
        JTable tabel2 = new JTable(data, columnNames);
        jScrollPane4.setViewportView(tabel2);
        tabel2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tabel2.rowAtPoint(e.getPoint());
                int cols = tabel2.columnAtPoint(e.getPoint());
                if (row >= 0 && cols >= 0) {
                    labId2.setText(pinjam2[row][3].toString());
                    labJudul2.setText(pinjam2[row][4].toString());
                    labNama2.setText(pinjam2[row][1].toString());
                }
            }
        });
    }

    private void tampilTabelPinjam2() {
        String[] columnNames = {"NIM", "Nama", "No Telp", "ID Buku", "Judul Buku", "Status", "Tanggal Pinjam", "Tanggal Pengembalian"};
        JTable tabel1 = new JTable(init.getData(pinjam2, "SELECT * FROM datapinjaman", 8), columnNames);
        jScrollPane4.setViewportView(tabel1);
    }

    public void tampilTabel() {
        String[] columnNames = {"ID Buku", "Judul Buku", "Penulis", "Tahun Terbit", "Genre", "Status"};
        JTable tabel1 = new JTable(init.getData(buku, "SELECT * FROM buku", 6), columnNames);
        jScrollPane1.setViewportView(tabel1);
    }

    public void tampilTabelClick() {
        String[] columnNames = {"ID Buku", "Judul Buku", "Penulis", "Tahun Terbit", "Genre", "Status"};
        JTable tabel1 = new JTable(init.getData(buku, "SELECT * FROM buku", 6), columnNames);
        jScrollPane2.setViewportView(tabel1);
        tabel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tabel1.rowAtPoint(e.getPoint());
                int cols = tabel1.columnAtPoint(e.getPoint());
                if (row >= 0 && cols >= 0) {
                    txtID1.setText(temp[row][0].toString());
                    txtJudul1.setText(temp[row][1].toString());
                    txtPenulis1.setText(temp[row][2].toString());
                    txtTerbit1.setText(temp[row][3].toString());
                    cmbGenre1.setSelectedItem(temp[row][4].toString());
                    txtStatus.setText(temp[row][5].toString());
                }
            }
        });
    }

    private void ubahPass() {
        try {
            init.Connection();

            PreparedStatement pStatement = init.conn.prepareStatement("UPDATE dblogin SET pass = ? WHERE username = 'admin'");
            pStatement.setString(1, txtPassbaru.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Ubah kata sandi berhasil!", "Information", JOptionPane.INFORMATION_MESSAGE);
                new App().setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(this, "Silahkan Login kembali!!", "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Ubah kata sandi gagal!", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            txtPasslama.setText("");
            txtPassbaru.setText("");
            txtPassbaru2.setText("");
            init.conn.close();
        } catch (SQLException e) {
            System.out.println("Error " + e.toString());
        }
    }

    private void autoComboBox() {
        try {
            init.Connection();
            DecimalFormat df = new DecimalFormat("000");
            int temp = 1;
            int index = 0;
            String id;

            for (int i = 1; i <= 999; i++) {
                id = df.format(i);
                PreparedStatement pSt = init.conn.prepareStatement("SELECT * FROM buku WHERE id_buku LIKE '__" + id + "'");
                ResultSet rs = pSt.executeQuery();
                String item = df.format(temp);
                temp++;
                if (!rs.next()) {;
                    cmbID.insertItemAt(item, index);
                    index++;
                }
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private Boolean cekIdBuku() {
        boolean cekIdBuku = false;
        try {
            init.Connection();

            PreparedStatement pStatement = init.conn.prepareStatement("SELECT * FROM buku WHERE id_buku = ?");
            pStatement.setString(1, "BK" + cmbID.getSelectedItem().toString());
            ResultSet rs = pStatement.executeQuery();

            if (rs.next()) {
                cekIdBuku = false;
            } else {
                cekIdBuku = true;
            }
            pStatement.close();
            init.conn.close();
        } catch (SQLException e) {
            System.out.println("Error " + e.toString());
        }
        return cekIdBuku;
    }
}
