package pinjamnovel;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Septa_Hendrawan
 */
public class SignUp extends javax.swing.JFrame {
        init init = new init();
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        pnl_Overlay.setBackground(new Color(0,0,0,200));
        this.setLocationRelativeTo(null);
        cmbTahun.setSelectedIndex(40);
        txtNIM.setDocument(new init.JTextFieldLimit(15));
        txtNoTelp.setDocument(new init.JTextFieldLimit(13));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Overlay = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        pnl_Singin = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        lab_Nim = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        lab_date = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        labName = new javax.swing.JLabel();
        labMajor = new javax.swing.JLabel();
        cmbTgl = new javax.swing.JComboBox<>();
        cmbBulan = new javax.swing.JComboBox<>();
        cmbTahun = new javax.swing.JComboBox<>();
        labAddress = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNoTelp = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbJurusan = new javax.swing.JComboBox<>();
        lab_1 = new javax.swing.JLabel();
        lab_2 = new javax.swing.JLabel();
        Background_laptop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1080, 650));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Overlay.setBackground(new java.awt.Color(0, 0, 0));
        pnl_Overlay.setInheritsPopupMenu(true);
        pnl_Overlay.setMinimumSize(new java.awt.Dimension(1080, 650));
        pnl_Overlay.setPreferredSize(new java.awt.Dimension(1080, 650));
        pnl_Overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        pnl_Overlay.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, -1, -1));

        pnl_Singin.setBackground(new java.awt.Color(32, 33, 35));
        pnl_Singin.setPreferredSize(new java.awt.Dimension(380, 150));
        pnl_Singin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitle.setBackground(new java.awt.Color(32, 33, 35));
        labTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labTitle.setForeground(new java.awt.Color(255, 255, 255));
        labTitle.setText("Create Account");
        pnl_Singin.add(labTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        lab_Nim.setBackground(new java.awt.Color(32, 33, 35));
        lab_Nim.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lab_Nim.setForeground(new java.awt.Color(255, 255, 255));
        lab_Nim.setText("NIM");
        pnl_Singin.add(lab_Nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtNIM.setBackground(new java.awt.Color(32, 33, 35));
        txtNIM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNIM.setForeground(new java.awt.Color(255, 255, 255));
        txtNIM.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIMKeyPressed(evt);
            }
        });
        pnl_Singin.add(txtNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 330, -1));

        lab_date.setBackground(new java.awt.Color(32, 33, 35));
        lab_date.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lab_date.setForeground(new java.awt.Color(255, 255, 255));
        lab_date.setText("Date of Birth");
        pnl_Singin.add(lab_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtNama.setBackground(new java.awt.Color(32, 33, 35));
        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnl_Singin.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 330, -1));

        labName.setBackground(new java.awt.Color(32, 33, 35));
        labName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labName.setForeground(new java.awt.Color(255, 255, 255));
        labName.setText("Name");
        pnl_Singin.add(labName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        labMajor.setBackground(new java.awt.Color(32, 33, 35));
        labMajor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labMajor.setForeground(new java.awt.Color(255, 255, 255));
        labMajor.setText("Major");
        pnl_Singin.add(labMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        cmbTgl.setBackground(new java.awt.Color(32, 33, 35));
        cmbTgl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbTgl.setForeground(new java.awt.Color(32, 33, 35));
        cmbTgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        cmbTgl.setBorder(null);
        pnl_Singin.add(cmbTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 50, -1));

        cmbBulan.setBackground(new java.awt.Color(32, 33, 35));
        cmbBulan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbBulan.setForeground(new java.awt.Color(32, 33, 35));
        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbBulan.setBorder(null);
        pnl_Singin.add(cmbBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 50, -1));

        cmbTahun.setBackground(new java.awt.Color(32, 33, 35));
        cmbTahun.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbTahun.setForeground(new java.awt.Color(32, 33, 35));
        cmbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        cmbTahun.setBorder(null);
        pnl_Singin.add(cmbTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        labAddress.setBackground(new java.awt.Color(32, 33, 35));
        labAddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labAddress.setForeground(new java.awt.Color(255, 255, 255));
        labAddress.setText("Address");
        pnl_Singin.add(labAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        txtAlamat.setBackground(new java.awt.Color(32, 33, 35));
        txtAlamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnl_Singin.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 330, -1));

        jLabel7.setBackground(new java.awt.Color(32, 33, 35));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");
        pnl_Singin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        txtNoTelp.setBackground(new java.awt.Color(32, 33, 35));
        txtNoTelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNoTelp.setForeground(new java.awt.Color(255, 255, 255));
        txtNoTelp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoTelpKeyPressed(evt);
            }
        });
        pnl_Singin.add(txtNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 330, -1));

        btnNext.setBackground(new java.awt.Color(126, 87, 194));
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.setBorder(null);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnl_Singin.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 80, 30));

        jLabel8.setBackground(new java.awt.Color(32, 33, 35));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(126, 87, 194));
        jLabel8.setText("Sing in instead");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        pnl_Singin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 90, 30));

        cmbJurusan.setBackground(new java.awt.Color(32, 33, 35));
        cmbJurusan.setForeground(new java.awt.Color(32, 33, 35));
        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi", "Teknik Industri", "Teknik Perangkat Lunak", "Teknik Elektro", "Akuntansi", "Manajemen", "Administrasi Bisnis", "Sastra inggris", "Ilmu Komunikasi", "Bahasa Inggris" }));
        cmbJurusan.setSelectedItem("");
        cmbJurusan.setToolTipText("");
        cmbJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_Singin.add(cmbJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 330, -1));

        pnl_Overlay.add(pnl_Singin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 430, 575));
        pnl_Singin.getAccessibleContext().setAccessibleName("");

        lab_1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lab_1.setForeground(new java.awt.Color(255, 255, 255));
        lab_1.setText("UAS Project");
        pnl_Overlay.add(lab_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lab_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lab_2.setForeground(new java.awt.Color(255, 255, 255));
        lab_2.setText("Registration Form");
        pnl_Overlay.add(lab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        getContentPane().add(pnl_Overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background_laptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Laptop Background.png"))); // NOI18N
        getContentPane().add(Background_laptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 350, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
        new App().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        SignUpNext x = new SignUpNext();
        if (txtNIM.getText().equals("") || txtNama.getText().equals("") || cmbJurusan.getSelectedItem().toString().equals("") || txtAlamat.getText().equals("") || txtNoTelp.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukan data terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (init.cek("SELECT * FROM dblogin WHERE nim = ?", txtNIM.getText()) == false) {
            JOptionPane.showMessageDialog(this, "NIM telah terdaftar", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String TglLahir = cmbTahun.getSelectedItem().toString() + "-" +
                    cmbBulan.getSelectedItem().toString() + "-" +
                    cmbTgl.getSelectedItem().toString();
            x.nim = txtNIM.getText();
            x.nama = txtNama.getText();
            x.jurusan = cmbJurusan.getSelectedItem().toString();
            x.tgl_lahir = TglLahir;
            x.alamat = txtAlamat.getText();
            x.no_telp = txtNoTelp.getText();
            this.dispose();
            x.show();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void txtNIMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIMKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
               txtNIM.setEditable(true);
            } else if (evt.getKeyCode() == KeyEvent.VK_BACKSPACE){
               txtNIM.setEditable(true);
            } else {
                txtNIM.setEditable(false);
            }
    }//GEN-LAST:event_txtNIMKeyPressed

    private void txtNoTelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTelpKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
                txtNoTelp.setEditable(true);
            } else if (evt.getKeyCode() == KeyEvent.VK_BACKSPACE){
               txtNoTelp.setEditable(true);
            } else {
                txtNoTelp.setEditable(false);
            }
    }//GEN-LAST:event_txtNoTelpKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_laptop;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cmbBulan;
    public javax.swing.JComboBox<String> cmbJurusan;
    private javax.swing.JComboBox<String> cmbTahun;
    private javax.swing.JComboBox<String> cmbTgl;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labAddress;
    private javax.swing.JLabel labMajor;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel lab_1;
    private javax.swing.JLabel lab_2;
    private javax.swing.JLabel lab_Nim;
    private javax.swing.JLabel lab_date;
    private javax.swing.JPanel pnl_Overlay;
    private javax.swing.JPanel pnl_Singin;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTelp;
    // End of variables declaration//GEN-END:variables
}
