package pinjamnovel;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Septa_Hendrawan
 */
public class SignUpNext extends javax.swing.JFrame {
        init init = new init();
        String nim, nama, jurusan, tgl_lahir, alamat, no_telp;
    /**
     * Creates new form SignUpNext
     */
    public SignUpNext() {
        initComponents();
        pnl_Overlay.setBackground(new Color(0,0,0,200));
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Overlay = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        pnl_Singin = new javax.swing.JPanel();
        lab_title = new javax.swing.JLabel();
        lab_username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lab_Password = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lab_ConfirmPassword = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        lab_back = new javax.swing.JLabel();
        lab_1 = new javax.swing.JLabel();
        lab_2 = new javax.swing.JLabel();
        Background_laptop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1080, 650));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Overlay.setBackground(new java.awt.Color(0, 0, 0));
        pnl_Overlay.setInheritsPopupMenu(true);
        pnl_Overlay.setMinimumSize(new java.awt.Dimension(1080, 650));
        pnl_Overlay.setPreferredSize(new java.awt.Dimension(1080, 650));
        pnl_Overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        pnl_Overlay.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, -1, -1));

        pnl_Singin.setBackground(new java.awt.Color(32, 33, 35));
        pnl_Singin.setPreferredSize(new java.awt.Dimension(380, 150));
        pnl_Singin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_title.setBackground(new java.awt.Color(32, 33, 35));
        lab_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lab_title.setForeground(new java.awt.Color(255, 255, 255));
        lab_title.setText("Create Account");
        pnl_Singin.add(lab_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        lab_username.setBackground(new java.awt.Color(32, 33, 35));
        lab_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lab_username.setForeground(new java.awt.Color(255, 255, 255));
        lab_username.setText("Username");
        pnl_Singin.add(lab_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtUsername.setBackground(new java.awt.Color(32, 33, 35));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnl_Singin.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 330, -1));

        lab_Password.setBackground(new java.awt.Color(32, 33, 35));
        lab_Password.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lab_Password.setForeground(new java.awt.Color(255, 255, 255));
        lab_Password.setText("Password");
        pnl_Singin.add(lab_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtPassword.setBackground(new java.awt.Color(32, 33, 35));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnl_Singin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 330, -1));

        lab_ConfirmPassword.setBackground(new java.awt.Color(32, 33, 35));
        lab_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lab_ConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lab_ConfirmPassword.setText("Confirm Password");
        pnl_Singin.add(lab_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtConfirmPassword.setBackground(new java.awt.Color(32, 33, 35));
        txtConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnl_Singin.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 330, -1));

        btnSave.setBackground(new java.awt.Color(126, 87, 194));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Finish");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnl_Singin.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 80, 30));

        lab_back.setBackground(new java.awt.Color(32, 33, 35));
        lab_back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lab_back.setForeground(new java.awt.Color(126, 87, 194));
        lab_back.setText("Back");
        lab_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_backMouseClicked(evt);
            }
        });
        pnl_Singin.add(lab_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 90, 30));

        pnl_Overlay.add(pnl_Singin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 430, 575));
        pnl_Singin.getAccessibleContext().setAccessibleName("");

        lab_1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lab_1.setForeground(new java.awt.Color(255, 255, 255));
        lab_1.setText("UAS Project");
        pnl_Overlay.add(lab_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lab_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lab_2.setForeground(new java.awt.Color(255, 255, 255));
        lab_2.setText("Registration Form");
        pnl_Overlay.add(lab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        getContentPane().add(pnl_Overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background_laptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Laptop Background.png"))); // NOI18N
        getContentPane().add(Background_laptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 350, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void lab_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_backMouseClicked
        this.dispose();
        new SignUp().setVisible(true);
    }//GEN-LAST:event_lab_backMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (init.cek("SELECT * FROM dblogin WHERE username = ?", txtUsername.getText()) == false) {
            JOptionPane.showMessageDialog(this, "Username Telah Digunakan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukkan Password Anda", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (txtConfirmPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Konfirmasi Password Anda", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukkan Username Anda", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (!(Arrays.equals(txtPassword.getPassword(), txtConfirmPassword.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Password yang anda masukan tidak sama", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            insertDblogin();
            insertMahasiswa();
            JOptionPane.showMessageDialog(this, "Daftar berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);

            new App().show();
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
   
    private void insertMahasiswa() {
        try {
            init.Connection();

            PreparedStatement pStatement = init.conn.prepareStatement("INSERT INTO mahasiswa (nim,nama,jurusan,tgl_lahir,alamat,no_telp) VALUES (?,?,?,?,?,?)");
            pStatement.setString(1, nim);
            pStatement.setString(2, nama);
            pStatement.setString(3, jurusan);
            pStatement.setString(4, tgl_lahir);
            pStatement.setString(5, alamat);
            pStatement.setString(6, no_telp);
            
            if (pStatement.executeUpdate() > 0) {
            } else {
                JOptionPane.showMessageDialog(this, "Penambahan Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            
            pStatement.close();
            init.conn.close();
        } catch (SQLException e) {
            System.out.println("Error " + e.toString());
        }
    }

    private void insertDblogin() {
        try {
            init.Connection();

            PreparedStatement pStatement = init.conn.prepareStatement("INSERT INTO dblogin (nim,username,pass) VALUES (?,?,?)");
            pStatement.setString(1, nim);
            pStatement.setString(2, txtUsername.getText());
            pStatement.setString(3, txtPassword.getText()); 
            
            if (pStatement.executeUpdate() > 0) {
            } else {
                JOptionPane.showMessageDialog(this, "Penambahan Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            
            pStatement.close();
            init.conn.close();

        } catch (SQLException e) {
            System.out.println("Koneksi Gagal " + e.toString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_laptop;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel lab_1;
    private javax.swing.JLabel lab_2;
    private javax.swing.JLabel lab_ConfirmPassword;
    private javax.swing.JLabel lab_Password;
    private javax.swing.JLabel lab_back;
    private javax.swing.JLabel lab_title;
    private javax.swing.JLabel lab_username;
    private javax.swing.JPanel pnl_Overlay;
    private javax.swing.JPanel pnl_Singin;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
